print('hello')
raise Exception('hello exception!')